---
application:
  name: 'sigle'
  project: 'sigle'
  organization: 'QoveryCommunity'
  dockerfile: Dockerfile
routers:
  - name: 'main-sigle'
    custom_domains:
      - branch: master
        domain: dev.sigle.io
    routes:
      - application_name: 'sigle'
        paths:
          - '/'
