language: node_js

notifications:
  email: false

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '11'

install:
  - yarn install --pure-lockfile

script:
  # Build the client
  - yarn build
  # Run the tests
  - yarn test
  # Check if the files are formatted
  - yarn test:prettier
