language: node_js

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache

node_js:
  - '11'

install:
  - yarn install --pure-lockfile

script:
  # Build the client
  - yarn build
  # Run the tests
  - yarn test
