version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db_data:
